### PR TITLE
Added theme neutral icons for some social sites

### PR DESCRIPTION
**Pull request by MaheshBharadwaj**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Enhancement
- [ ] Documentation Update

## Description
Due to github dark mode, social icons would not be visible
**NOTE:**
The icons would be changed only in the preview and the generated .md text, the website still retains the black icons as they are uniform

## Output
Screenshot from 2021-01-15 21-37-59

## Added to documentation?

- [ ] readme

## PS IMPORTANT
You would have to change icon_base_url after merging in order to point to the main repository, I have pointed it to my fork for the test site alone : D

### CODE REVIEW

**Comment by akkshaylawrence** [comment]
What is your opinion on using icons from [simpleicons](https://simpleicons.org)? IMO it looks more consistent.

**Comment by MaheshBharadwaj** [comment]
> What is your opinion on using icons from [simpleicons](https://simpleicons.org)? IMO it looks more consistent.

Which is what was being used, the icons are all black in color and werent visible in github's dark mode

**Comment by rahuldkjain** [comment]
Hey @MaheshBharadwaj, sorry for replying so late.
I would suggest to use CDN links from [WorldVectorLogo](https://worldvectorlogo.com/)

For example:
https://worldvectorlogo.com/search/Discord

Let's not add a dependency on your personal repo

**Comment by MaheshBharadwaj** [comment]
No No it wouldnt depend on my personal repo, after PR you would have to change the link to your repo here that's all cause Im pushing the SVG icons also 
But if you want CDN, then close this PR, ill open a new one with CDN

**Comment by rahuldkjain** [comment]
Oh got it.

**Review by rahuldkjain — APPROVED** [review]
Thanks a lot @MaheshBharadwaj 🙏

**Pull request merged**
