### PR TITLE
change gatsby-plugin-sharp version

### PR DESCRIPTION
**Pull request by Mohitmadhav**
Changed the gatsby version

### CODE REVIEW

**Comment by rahuldkjain** [comment]
@Mohitmadhav Please mention issue number in the description

**Review by rahuldkjain — APPROVED** [review]
Cool @Mohitmadhav.

**Comment by Mohitmadhav** [comment]
> @Mohitmadhav Please mention the issue number in the description

Really sorry for that
It is Issue #228

**Review by rahuldkjain — APPROVED** [review]
Great @Mohitmadhav.

**Pull request merged**
