### PR TITLE
Fixes for Issue ID: 128

### PR DESCRIPTION
**Pull request by jaideepghosh**
This PR includes:
• Anchor tag on skills in markdown preview and in the the generated markdown.

### CODE REVIEW

**Comment by jaideepghosh** [comment]
Hey @rahuldkjain 
Please have a look on the fixes of Issued id [128](https://github.com/rahuldkjain/github-profile-readme-generator/issues/128)

**Review by rahuldkjain — APPROVED** [review]
Superb @jaideepghosh 💯.
Please make sure to become the assignee of the issue before opening a PR.

Join the discord server for further discussions related to this project and Hacktoberfest.
Server Link: https://discord.gg/HHMs7Eg

**Comment by jaideepghosh** [comment]
Hey @rahuldkjain 
Let me know how to become a assignee of the issue? Seems like I don't have permissions for that in this repo.

**Comment by rahuldkjain** [comment]
> Hey @rahuldkjain
> Let me know how to become an assignee of the issue? Seems like I don't have permissions for that in this repo.

You can't assign yourself. You have to go the issues page and leave a comment like `I want to contribute to solve this issue. Please assign it to me`.
Then I will assign it to you.

**Comment by jaideepghosh** [comment]
Thanks @rahuldkjain

**Pull request merged**
