### PR TITLE
fixed social icons

### PR DESCRIPTION
**Pull request by Shrestha7**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Enhancement
- [ ] Documentation Update

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added to documentation?

- [ ] readme

### CODE REVIEW

**Review by harshcut — APPROVED** [review]

**Comment by Shrestha7** [comment]
bugfix  Issues : [https://github.com/rahuldkjain/github-profile-readme-generator/issues/385](url)

**Review by vikasvmane — APPROVED** [review]

**Review by rahuldkjain — APPROVED** [review]
Thanks for this quick bug fix @Shrestha7

**Comment by Estelle544** [comment]
70d473ca9194ad352898149ee023f799eabfddce

**Review by Estelle544 — COMMENTED** [review]
Thank you

**Comment by Estelle544** [comment]
Love

**Comment by Estelle544** [comment]
Thanks

**Comment by Estelle544** [comment]
d8139bc7e29acf777ca10e673ad76c75191bc900

**Review by Estelle544 — COMMENTED** [review]
Thanks

**Comment by Estelle544** [comment]
d8139bc7e29acf777ca10e673ad76c75191bc900

**Pull request merged**
