### PR TITLE
fixed ESLintError warnings in local dev environment #279

### PR DESCRIPTION
**Pull request by Mamoanwar97**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Enhancement
- [ ] Documentation Update

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added to documentation?

- [ ] readme

### CODE REVIEW

**Comment by zenby** [comment]
Please, resolve merge conflicts, also as I see changes in `yarn-lock.json` are not required.

**Comment by mamoanwar97** [comment]
i resolved the conflicts

**Comment by mamoanwar97** [comment]
@zenby solved the conflict and runs with no warnings

**Review by zenby — APPROVED** [review]
LGTM!

**Review by mamoanwar97 — COMMENTED** [review]
Thank you ^^

**Comment by zenby** [comment]
@mamoanwar97 please update your branch with master to have all the checks green.
Also as I remember it will be marked as hacktoberfest accepted PR because you've opened it in october.

**Pull request closed without merging**
