### PR TITLE
fix: #158 aligns titles to the left

### PR DESCRIPTION
**Pull request by shajanjp**
Left-aligned titles gets more attraction from the user.

### CODE REVIEW

**Comment by rahuldkjain** [comment]
@shajanjp Please open the issue before making any pull-request.
Mention the issue number in the comments here, once you open an issue regarding this PR.
Then I will review and approve it.

**Comment by rahuldkjain** [comment]
Join Discord Server for discussing issues, pull-requests, new features, etc.

Discord Server Link- https://discord.gg/HHMs7Eg

**Comment by shajanjp** [comment]
This closes #158

**Review by g-savitha — APPROVED** [review]
looks good to me. :)  thanks for contributing @shajanjp

**Pull request merged**
