### PR TITLE
feat: added option to add replit username in social

### PR DESCRIPTION
**Pull request by varun7singh**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Enhancement
- [ ] Documentation Update

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added to documentation?

- [ ] readme

### CODE REVIEW

**Comment by HashtagDevM** [comment]
The Social links are not populating after clicking on Generate. Not Replit not the others.
Screenshot 2022-10-01 at 11 24 02
Screenshot 2022-10-01 at 11 24 46

**Comment by varun7singh** [comment]
Where do i get the replit.svg we need to add that to images/social for displaying @HashtagDevM

**Comment by HashtagDevM** [comment]
@varun7singh - https://commons.wikimedia.org/wiki/File:Repl.it_logo.svg

**Comment by varun7singh** [comment]
image
everything else is working fine just this svg is not rendering every other icon in the Social folder is getting rendered

**Pull request closed without merging**
