### PR TITLE
Fix social icons base link

### LINKED ISSUE #382: Twitter svg error
While adding twitter profile link, the image is not loading.

404: Not Found
https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/neutral-icons/src/images/icons/Social/twitter.svg

### PR DESCRIPTION
**Pull request by PuneetGopinath**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Enhancement
- [ ] Documentation Update

## Description

Fixes #382

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added to documentation?

- [ ] readme

### CODE REVIEW

**Review by harshcut — APPROVED** [review]
LGTM 👍

**Comment by PuneetGopinath** [comment]
> LGTM 👍

I think you meant Looks Good?

**Comment by PuneetGopinath** [comment]
> LGTM 👍

Well, I also have doubt whether this pr, solves #378
Because when I browsed https://github-profile-git-fork-puneetgopinath-patch-1-rahu-fcad96.vercel.app/
I didn't do anything related to it, but that bug it solved?

**Comment by PuneetGopinath** [comment]
> Well, I also have doubt whether this pr, solves #378
> Because when I browsed https://github-profile-git-fork-puneetgopinath-patch-1-rahu-fcad96.vercel.app/
> I didn't do anything related to it, but that bug it solved?

Does it fix #378 also?

**Comment by harshcut** [comment]
> Does it fix #378 also?

No. The [`mssql`](https://cdn.worldvectorlogo.com/logos/microsoft-sql-server.svg) icon is broken from its source.

image

**Comment by PuneetGopinath** [comment]
> No. The [`mssql`](https://cdn.worldvectorlogo.com/logos/microsoft-sql-server.svg) icon is broken from its source.
> 
> image
See https://github-profile-git-fork-puneetgopinath-patch-1-rahu-fcad96.vercel.app/
Your screenshot shows that you are in another url
See the below image
image

**Comment by harshcut** [comment]
I checked [this](https://github-profile-git-fork-puneetgopinath-patch-1-rahu-fcad96.vercel.app/) too and it's still broken. Check the svg source from inspect element, it should be broken.

**Comment by PuneetGopinath** [comment]
No, the source is https://cdn.worldvectorlogo.com/logos/microsoft-sql-server.svg
Preview: image

**Comment by harshcut** [comment]
I'm having this output.

image

**Comment by PuneetGopinath** [comment]
Is it?
Looks like you use Microsoft edge, I will try in Microsoft edge afterwards.
If you have chrome, I think you can try in chrome.
Or see the preview of the comment in my GitHub android:
image

**Pull request merged**
