### PR TITLE
Added kotlin to programming languages

### PR DESCRIPTION
**Pull request by Porush**
@g-savitha, I am creating this PR in response to issue #189 assigned to me.

### CODE REVIEW

**Comment by g-savitha** [comment]
kotlin is already present under mobile dev section.

**Comment by Porush** [comment]
@g-savitha, Sorry i didn't notice it before. I removed kotlin from mobile dev section because it is misleading to put it with SDKs like Flutter, It should be in programming language section.

**Comment by g-savitha** [comment]
ok

**Comment by harshcut** [comment]
Closing the Pull Request due to duplicate additions.
Is this a mistake? Open a new Pull Request linking this PR for reference.

**Pull request closed without merging**
