### PR TITLE
update footer to be responsive

### PR DESCRIPTION
**Pull request by pollyj**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Enhancement
- [ ] Documentation Update

## Description
This PR fixes the footer so that it displays responsively on mobile.

## Related Tickets & Documents
#262 

## QA Instructions, Screenshots, Recordings
[Image from Gyazo](https://gyazo.com/4705a3383ee50cedda65693d1a61ce63)

## Added to documentation?
n/a

### CODE REVIEW

**Review by rahuldkjain — CHANGES_REQUESTED** [review]
@pollyj I would suggest you to please add left-margin to links. Make the `GitHub Profile README Generator` aligned with the links too(not centered). You can increase the font-size of the same too.

**Comment by pollyj** [comment]
@rahuldkjain Thanks for the feedback! I've implemented the changes you requested. Please let me know if you'd like anything else changed.

**Review by rahuldkjain — CHANGES_REQUESTED** [review]
Please reduce the font-weight or color of links (addons, support, about, GitHub, releases).

**Comment by pollyj** [comment]
@rahuldkjain I've changed the font weight. The previous font only imported the regular font weight so I added a lighter version from google, hope that's okay. Please let me know if you would like any other changes.

**Review by rahuldkjain — APPROVED** [review]
Looks great @pollyj.

**Pull request merged**
