### PR TITLE
update gif in readme

### PR DESCRIPTION
**Pull request by g-savitha**
Updated gif with new changes 

Fix for : https://github.com/rahuldkjain/github-profile-readme-generator/issues/79#issuecomment-697202104

### CODE REVIEW

**Review by rahuldkjain — COMMENTED** [review]
No need to add the whole LinkedIn profile URL. You can add LinkedIn by username only.

And can we make the preview-markdown a little longer?

**Review by rahuldkjain — CHANGES_REQUESTED** [review]
Please fix the LinkedIn URL with the username

**Comment by g-savitha** [comment]
ok will do that

**Comment by g-savitha** [comment]
can you mark this also under hacktoberfest tag. Will do this as a part of that

**Comment by rahuldkjain** [comment]
@g-savitha sure

**Comment by g-savitha** [comment]
cool thanks

**Comment by g-savitha** [comment]
will raise a new pr for this. hence closing

**Pull request closed without merging**
