### PR TITLE
Rss integration

### PR DESCRIPTION
**Pull request by g-savitha**

### CODE REVIEW

**Comment by rahuldkjain** [comment]
@g-savitha I am not able to review the changes due to the prettier thing. Could you please update the PR with only the required changes?

**Comment by g-savitha** [comment]
This commit has changes specific to this Enhancement https://github.com/rahuldkjain/github-profile-readme-generator/commit/50a97f7d128d497d9489a02378ea4dcd31d7fc95

**Comment by g-savitha** [comment]
Or will close this PR and raise a new one with respective changes

**Comment by rahuldkjain** [comment]
Close this one and mention the issue in the description of the new PR

**Comment by g-savitha** [comment]
ok cool

**Pull request closed without merging**
