### PR TITLE
Regex for Twitter Username Validation

### PR DESCRIPTION
**Pull request by Maddoxx88**

### CODE REVIEW

**Comment by rahuldkjain** [comment]
@Maddoxx88 
Screenshot 2020-10-04 at 5 06 28 PM

**Comment by Maddoxx88** [comment]
Resolving

**Comment by Maddoxx88** [comment]
Done. @rahuldkjain 
Sorry for the delay!

**Comment by rahuldkjain** [comment]
@Maddoxx88 Please mention the issue-number.

**Comment by Maddoxx88** [comment]
Added Twitter Username Validation mentioned in #216

**Comment by Maddoxx88** [comment]
Wait one last change is remaining @rahuldkjain

**Comment by Maddoxx88** [comment]
> @Maddoxx88 Please mention the issue-number.

Added Twitter Username Validation mentioned in #216

**Review by rahuldkjain — APPROVED** [review]
Great @Maddoxx88.

**Pull request merged**
