### PR TITLE
Enhancement: Added Matlab SVG

### LINKED ISSUE #205: Add some missing logos
Add the Arduino logo in others section.
[Arduino Logo](https://cdn.worldvectorlogo.com/logos/arduino-1.svg)

Add the MATLAB logo in the programming languages section.
[MATLAB Logo](https://img.icons8.com/nolan/420/matlab.png)

Add the Solidworks logo in the software section.
[Solidworks Logo](https://cdn.worldvectorlogo.com/logos/solidworks.svg)

### PR DESCRIPTION
**Pull request by Aditya-ds-1806**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Enhancement
- [ ] Documentation Update

## Description
I managed to generate the matlab logo in by running some code in MATLAB and then exported the image to svg. I hosted it on a free svg hosting provider called svgshare. The image is here: https://svgshare.com/i/QFw.svg.

## Related Tickets & Documents
Fixes #205.

## QA Instructions, Screenshots, Recordings
UI changes
image

## Added to documentation?

- [ ] readme

### CODE REVIEW

**Comment by Aditya-ds-1806** [comment]
@rahuldkjain No feedback yet :(. Is my PR bad? Let me know so that I can improve.

**Review by rahuldkjain — APPROVED** [review]
Don't fix two issues one PR. I suggest you to please remove the fix for #225.
Rest is fine.

**Review by rahuldkjain — CHANGES_REQUESTED** [review]
Please remove the fix for #225

**Comment by Aditya-ds-1806** [comment]
Ok will do that

**Comment by Aditya-ds-1806** [comment]
@rahuldkjain I have made changes to the PR. Please check now.

**Comment by Aditya-ds-1806** [comment]
@rahuldkjain can u please merge this?

**Comment by Aditya-ds-1806** [comment]
Can u please merge this?

**Comment by Aditya-ds-1806** [comment]
@rahuldkjain I have made the changes, is it fine now?

**Review by rahuldkjain — APPROVED** [review]
Superb @Aditya-ds-1806.

**Pull request merged**
