### PR TITLE
feat: add option to upload json backup file

### PR DESCRIPTION
**Pull request by Tailine**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Enhancement
- [ ] Documentation Update

## Description
Add option to upload json backup file.
## Related Tickets & Documents
#103 
## QA Instructions, Screenshots, Recordings

upload

### CODE REVIEW

**Review by rahuldkjain — CHANGES_REQUESTED** [review]
I see that the changes required for this issue are in `index.js` only.
So @Tailine, I request you to please commit the changes of `index.js` only and unstage all other changes from this PR.

**Comment by Tailine** [comment]
@rahuldkjain Ok, I will figure it out how to do that

**Review by rahuldkjain — APPROVED** [review]
Superb @Tailine.

**Comment by Tailine** [comment]
Thanks @rahuldkjain

**Pull request merged**
