### PR TITLE
Re-design about page

### PR DESCRIPTION
**Pull request by lill74**
Issue #164 
@rahuldkjain I proofread it and change some layouts, typos, unused tags, and add some image to attract users. As a context, I think you've done well. But as a layout, there is something messy, so I just changed some layouts to highlight specific contexts. And I referenced some popular GitHub Repositories. 

- cli/cli
- facebook/react
- vuejs/vue
- tensorflow/tensorflow

### CODE REVIEW

**Comment by lill74** [comment]
687474703a2f2f692e696d6775722e636f6d2f647438415562362e706e67

**Review by rahuldkjain — CHANGES_REQUESTED** [review]
This PR don't follow the design-styleguide.

**Comment by harshcut** [comment]
Closing the Pull Request due to inactivity.
Is this a mistake? Open a new Pull Request linking this PR for reference.

**Pull request closed without merging**
