### PR TITLE
fix: trim data values before generate

### PR DESCRIPTION
**Pull request by rajat2502**
fixes: #12

### CODE REVIEW

**Comment by rahuldkjain** [comment]
@rajat2502 the social usernames are stored in `social` state not in `data` state. You are setting the wrong state.

Use this instead
```js
const trimDataValues = () => {
    const dataObj = { ...social };
    Object.keys(dataObj).forEach(k => (typeof dataObj[k] === 'string') ? dataObj[k] = dataObj[k].trim() : null);
    setSocial(dataObj);
  }
```

**Comment by rajat2502** [comment]
@rahuldkjain but the fields inside the 'data' state are in 'bold' in the markdown so we need to trim their values and not social links.

**Comment by rahuldkjain** [comment]
@rajat2502 my bad. I thought you are doing for both social and work category. Will review and merge the PR soon.
Thanks for the efforts

**Comment by rajat2502** [comment]
Thanks for the merge!

**Comment by rajat2502** [comment]
Btw do we have the same problem with social links?

**Pull request merged**
