### PR TITLE
Add skill Adobe Xd

### PR DESCRIPTION
**Pull request by abhaybhatt**
I added Adobe Xd in software section of skills.

### CODE REVIEW

**Comment by abhaybhatt** [comment]
@rahuldkjain please review it?

**Review by g-savitha — COMMENTED** [review]
Thanks for contributing @abhaybhatt . Have you tested it on both mobile and PC?

**Comment by g-savitha** [comment]
Please mention the issue number to which you are contributing

**Comment by abhaybhatt** [comment]
@g-savitha yes  i have tested it

**Comment by abhaybhatt** [comment]
@g-savitha  its issue no. #151

**Comment by harshcut** [comment]
You might want to close this Pull Request as this already exists.

**Comment by harshcut** [comment]
Closing the Pull Request due to duplicate additions.
Is this a mistake? Open a new Pull Request linking this PR for reference.

**Pull request closed without merging**
