### PR TITLE
Create HourGlassChallenge.md using 2D arrays

### PR DESCRIPTION
**Pull request by utkxxrsh**
HourGlassChallenge Using Arrays 2D

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Enhancement
- [ ] Documentation Update

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added to documentation?

- [ ] readme

### CODE REVIEW

**Comment by zenby** [comment]
@utkxxrsh Hello

What is the purpose of this PR?
Regarding the files changes I'd add `invalid` label to this pr or even close it. Because I don't feel it suits to this repo.

**Comment by utkxxrsh** [comment]
HI,
Evgeniy Dainovich





This PR was for a program that i created and thoud would countribute for
betterment of the repo I didnt know that it violate the guidelines or make
it invalid.
The sole purpose was to help the beginners through this repo.

**Comment by zenby** [comment]
I just say my opinion.
I think @rahuldkjain know what to do, and can deal with that.

**Comment by harshcut** [comment]
Closing the Pull Request due to spam.
Is this a mistake? Open a new Pull Request linking this PR for reference.

**Pull request closed without merging**
