### PR TITLE
Dev logo refactored to neutral colour

### PR DESCRIPTION
**Pull request by chandrikadeb7**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Enhancement
- [ ] Documentation Update

## Description
Refactored Dev.to logo to neutral colours

## Related Tickets & Documents
Fixes partially #345 

## QA Instructions, Screenshots, Recordings
Screenshot 2021-10-02 at 11 54 27 AM

## Added to documentation?

- [ ] readme

### CODE REVIEW

**Review by rahuldkjain — CHANGES_REQUESTED** [review]
Please use svg icon if possible.

**Comment by chandrikadeb7** [comment]
> Please use svg icon if possible.

Sorry. SVG uses black with transparent bg only.

**Comment by rahuldkjain** [comment]
@chandrikadeb7 we can use this svg logo https://d2fltix0v2e0sb.cloudfront.net/dev-rainbow.svg

**Comment by chandrikadeb7** [comment]
> @chandrikadeb7 we can use this svg logo https://d2fltix0v2e0sb.cloudfront.net/dev-rainbow.svg

I have changed please check

**Review by rahuldkjain — APPROVED** [review]
Awesome, thanks a lot @chandrikadeb7 🙌

**Pull request merged**
