### PR TITLE
fix paypal icon

### PR DESCRIPTION
**Pull request by harikanani**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Enhancement
- [ ] Documentation Update

## Description
    Fixed Broken Paypal Icon 
## Related Tickets & Documents
   PayPal icon link broken #365

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, as well
as any relevant images for UI changes._

## Added to documentation?

- [ ] readme

### CODE REVIEW

**Review by chaitanyasjoshi — APPROVED** [review]
Looks good

**Comment by harikanani** [comment]
@chaitanyasjoshi Merge PR if it resolves the issue!

**Comment by chaitanyasjoshi** [comment]
@harikanani I don't have permission to merge pr. Mods will take care of this

**Review by rahuldkjain — APPROVED** [review]
Looks good!

**Pull request merged**
