### PR TITLE
Add Appwrite BaaS

### PR DESCRIPTION
**Pull request by kodumbeats**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] Enhancement
- [ ] Documentation Update

## Description

Adds [Appwrite](https://appwrite.io) as a skill under BaaS. 

## Related Tickets & Documents

#367 
Previously discussed with Appwrite CEO

## QA Instructions, Screenshots, Recordings

muchbetter

## Added tests?

- [ ] yes
- [x] no, because they aren't needed
- [ ] no, because I need help

## Added to documentation?

- [ ] readme

### CODE REVIEW

**Comment by kodumbeats** [comment]
Is there anything I can do to help this along? Please let me know if there's anything I've missed for this PR. :)

**Review by rahuldkjain — CHANGES_REQUESTED** [review]
@kodumbeats Please use svg files instead of png.

**Comment by kodumbeats** [comment]
Thank you for the review! The requested changes are introduced in b7b1fd0.

**Review by rahuldkjain — APPROVED** [review]
LGTM.

**Pull request merged**
